# Generated by Django 4.2.4 on 2023-08-25 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$')])),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.company')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.contactinfo')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.contactinfo'),
        ),
    ]
